COMPONENT=OsrTestAppC

CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/4bitle \
          -I$(TOSDIR)/lib/net/ctp

CFLAGS += -I../../bflt \
		  -I../../osr \

CFLAGS += -DTOSH_DATA_LENGTH=100

include $(MAKERULES)
